Add support for the endpoint /challenge/{id}/addFileTasks, closes #83
osmlab/maproulette-python-client pull request #84
Opened 2021-08-11 07:41 UTC by rYR79435

This is my shot at implementing the endpoint I requested in #83.

I have used the [swagger documentation](https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json&docExpansion=none#/Challenge/addTasksToChallengeFromFile) for this.

Unfortuantely the API always returns `maproulette.api.errors.InvalidJsonError: {'status': 400, 'message': 'Invalid JSON payload.'}` no matter what I try. I have depleted my ideas for how to fix this, hence I'm creating this draft in hopes someone can help me.

Some notes:
- when I save my JSON to a file and then try to manually upload this via the MapRoulette UI (`Edit Challenge -> Change Name or Data Source -> upload GeoJSON file`), it works with no problems whatsoever (no errors, I can start tasks and they work as expected).
- I'm working with a Tag Fix challenge, my JSON is therefore in line-by-line format, as mentioned on [learn.maproulette.org](https://learn.maproulette.org/documentation/line-by-line-geojson/)
- when I use the web-based API test on [swagger](https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json&docExpansion=none#/Challenge/addTasksToChallengeFromFile), curl receives a `Missing boundary header` error. This is also true for curl on my local machine. I receive the same error whether I use the afforementioned JSON (that works in MR UI) or some (valid as well as invalid JSON) bogus data.

2021-08-15 14:57 UTC, rYR79435 commented
I figured out what the problem was. The API expects the file to be named 'json'.

2021-09-07 20:12 UTC, mattmanley reviewed
This is looking great. Would you mind adding a unit test to accompany this new method?

2021-09-08 10:58 UTC, rYR79435 commented
Sure thing!
Thank you for reviewing.

2021-09-08 20:18 UTC, mattmanley requested changes
Looking good! Thanks for adding the unit test. Just a couple of nits and question.

2021-09-08 20:18 UTC, mattmanley commented on maproulette/api/challenge.py
> +    def add_file_tasks_to_challenge(self, data, challenge_id, line_by_line="true", remove_unmatched="false", data_origin_date="", skip_snapshot="false"):
Could you split this line out to confirm to PEP 8 length restrictions?

2021-09-08 20:18 UTC, mattmanley commented on maproulette/api/challenge.py
> +        :param lineByLine: whether or not the provided data is in line-by-line GeoJSON format
Nit: lineByLine vs. line_by_line used here

2021-09-08 20:18 UTC, mattmanley commented on maproulette/api/challenge.py
> +        :param skipSnapshot: whether or not to skip recording a snapshot before proceeding
Nit: skipSnapshot vs. skip_snapshot used here

2021-09-08 20:18 UTC, mattmanley commented on maproulette/api/challenge.py
> +        body = {'json': ('data', data)} # server only accepts dict with key 'json'
Just curious, how are you processing the GeoJSON prior to passing it to this function. In other words, what type of object are you passing for this argument?

2021-09-09 10:31 UTC, rYR79435 commented on maproulette/api/challenge.py
> +        :param lineByLine: whether or not the provided data is in line-by-line GeoJSON format
Addressed in b0abbb1

2021-09-09 10:31 UTC, rYR79435 commented on maproulette/api/challenge.py
> +        :param skipSnapshot: whether or not to skip recording a snapshot before proceeding
Addressed in b0abbb1

2021-09-09 10:37 UTC, rYR79435 commented on maproulette/api/challenge.py
> +    def add_file_tasks_to_challenge(self, data, challenge_id, line_by_line="true", remove_unmatched="false", data_origin_date="", skip_snapshot="false"):
Addressed in ccc261d

2021-09-09 10:47 UTC, rYR79435 commented on maproulette/api/challenge.py
> +        body = {'json': ('data', data)} # server only accepts dict with key 'json'
A string containing valid line-by-line GeoJSON (multiple entries) or simply a Python dict (containing other dicts/arrays).

2022-06-07 15:08 UTC, mattmanley approved these changes

2022-06-07 15:08 UTC, merged